language: php

cache:
  apt: true

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  # Disable xdebug for better performance
  - phpenv config-rm xdebug.ini
  # Load frontend user management
  - git clone https://github.com/SchwarzwaldFalke/frontend-user-management ../frontend-user-management
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer update

script:
  - vendor/bin/phpunit