language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  # Load frontend user management
  - git clone https://github.com/SchwarzwaldFalke/frontend-user-management ../frontend-user-management
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=5.7.*"

script:
  - phpunit