language: php

cache:
  apt: true

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  # Disable xdebug for better performance
  - phpenv config-rm xdebug.ini
  - composer update
  - composer installTests

script:
  - vendor/bin/phpunit  -c tests/phpunit.xml